<?php

require_once __ROOT__ . 'routing/pRoute.php';

/**
 * Test class for pRoute.
 * Generated by PHPUnit on 2012-02-18 at 09:54:49.
 */
class pRouteTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pRoute
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pRoute('/testing/{home}', 'Home:helloWorld', 'POST', array('home' => '([a-zA-Z0-9])'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pRoute::httpMethod
     */
    public function testHttpMethod() {
        $this->assertEquals('POST', $this->object->httpMethod());
    }

    /**
     * @covers pRoute::rewrite
     */
    public function testRewrite() {
        $this->assertEquals('/testing/{home}', $this->object->rewrite());
    }

    /**
     * @covers pRoute::actual
     */
    public function testActual() {
        $this->assertEquals('Home:helloWorld', $this->object->actual());
    }

    /**
     * @covers pRoute::params
     */
    public function testParams() {
        $this->assertInstanceOf('pMap', $this->object->params());
        $this->assertCount(1, $this->object->params());
    }

}